// Options the user could type in
const prompts = [
  ["ram ram"],
  ["hi", "hey", "hello", "good morning", "good afternoon"],
  ["PG Department in College", "UG department in college", "how are things"],
  ["what are you doing", "what is going on", "what is up"],
  ["how old are you"],
  ["who are you", "are you human", "are you bot", "are you human or bot"],
  ["who created you", "who made you"],
  [
    "your name please",
    "your name",
    "may i know your name",
    "what is your name",
    "what call yourself"
  ],
  ["i love you"],
  ["happy", "good", "fun", "wonderful", "fantastic", "cool"],
  ["bad", "bored", "tired"],
  ["help me", "tell me story", "tell me joke"],
  ["ah", "yes", "ok", "okay", "nice"],
  ["bye", "good bye", "goodbye", "see you later"],
  ["what should i eat today"],
  ["bro"],
  ["what", "why", "how", "where", "when"],
  ["no","not sure","maybe","no thanks"],
  [""],
  ["haha","ha","lol","hehe","funny","joke"],
  ["departments","department","which departments are available"],
  ["courses","what are the available courses","courses list"],
  ["I want to know about admission process","admission procedure","admission","intake","student intake","admission process","what is admission process"],
  ["what is contact number for enquiry","enquiry","phone number","helpline","mail","college email id","contact details","how to contact college","how to contact","email","email id"],
  ["what is the address of college","college address","address","address of college"],
  ["placement information","placement","is college provide placements","job placements","placement cell","job","training","campus placements","campus placement","is campus placements in college","placements"],
  ["i want to see my result","result","can i see result","i want to know about result","my result","i want to know about my result"],
  ["timetable","time table","can i see timetable","i want to know about timetable","my timetable","i want to know about my timetable"],
  ["Madhuri Trikoti","madhuri trikoti","Trikoti Madhuri","trikoti madhuri"],
["Shreyash Laddha","shreyash laddha","Laddha Shreyash","laddha shreyash"],
["Gaurav Malewar","gaurav malewar","Malewar Gaurav","malewar gaurav"],
["Shivam Rewaskar","shivam rewaskar","Rewaskar Shivam","rewaskar shivam"],
["Prasad Deshmukh","prasad deshmukh","Deshmukh Prasad","deshmukh prasad"],
["Sumit Ghope","sumit ghope","Ghope Sumit","ghope sumit"],
["Jaydeep Pande","jaydeep pande","Pande Jaydeep","pande jaydeep"],
["Kedar Muley","kedar muley","Muley Kedar", "muley kedar"],
["Prathamesh Gulghane","prathamesh gulghane","Gulghane Prathamesh","gulghane prathamesh"],
["Nisarga Thakrey","nisarga thakrey","Thakrey Nisarga","thakrey nisarga"],

["Vinit Chandak","vinit chandak","Chandak Vinit","chandak vinit"],
["Soham Manekar","soham manekar","Manekar Soham","manekar soham"],
["Sumit Punse","sumit punse","Punse Sumit","Punse Sumit"],
["Rutuja Bhoge","rutuja bhoge","Bhoge Rutuja","bhoge rutuja"],
["Pratik Tayde","pratik tayde","Tayde Pratik","tayde pratik"],
["Vivek Shadi","vivek shadi","Shadi Vivek","shadi vivek"],
["Rudresh Deshpande","rudresh deshpande","Deshpande Rudresh","deshpande rudresh"],
["Anushka Ganjare","anushka ganjare","Ganjare Anushka","ganjare anushka"],
["Gaurav Agrawal","gaurav agrawal","Agrawal Gaurav","agrawal gaurav"],
["Abhishek Umratkar","abhishek umratkar","Umratkar Abhishek","umratkar abhishek"],
["Abhijeet Gandodhar","abhijeet gandodhar","Gandodhar Abhijeet","gandodhar abhijeet"],
["Sakshi Vighe","sakshi vighe","Vighe Sakshi","vighe sakshi"],
["Anmol Agrawal","anmol agrawal","Agrawal Anmol","agrawal anmol"],
["Aditya Pawar","aditya pawar","Pawar Aditya","pawar aditya"],
["Anam Ifrah","anam ifrah","Ifrah Anam","ifrah anam"],
["Purva Apale","purva apale","Apale Purva","apale purva"],
["Gauri Rewatkar","gauri rewatkar","Rewatkar Gauri","rewatkar gauri"],
["Walmikee Dhopte","walmikee dhopte","Dhopte Walmikee","dhopte walmikee"],
["Bhagyashree Shirbhate","bhagyashree shirbhate","Shirbhate Bhagyashree","shirbhate bhagyashree"],

["Krutika Agale","krutika agale","Agale Krutika","agale krutika"],
["Aniket Eche ","aniket eche","Eche Aniket","eche aniket"],
["Sumit Punse ","sumit punse ","Punse Sumit","punse sumit"],
["Nisarga Thakrey","Nisarga Thakrey","Thakrey Nisarga","thakrey nisarga"],
["Anmol Agrawal","anmol agrawal","Agrawal Anmol","agrawal anmol"],
["Purva Sharma","purva sharma","Sharma Purva","sharma purva"],
["Sakshi Vighe","sakshi vighe","Vighe Sakshi","vighe sakshi"],
["Sumit Ghope","sumit ghope","Punse Ghope","Punse Ghope"],
["Himanshu Raut","himanshu raut","Raut Himanshu","raut himanshu"],
["Vaibhav Jadhao","vaibhav jadhao","Jadhav Vaibhav","jadhav vaibhav"],
["Prachi Pohokar","prachi pohokar","Pohokar Prachi","pohokar prachi"],

["who is the principal"],
["who is the HOD of CSE department"],
["placement of 2019/2020"],
["Class sections in CSE department"],
["Final year section A class teacher"],
["Which grade is awarded by NAAC to the college"],
["Who is the chairman"],
["college was founded in which year"],
["Rank given by NIRF"],
["fee structure"],
["Result link"],
["Intake capacity for CSE"],
["Exam form link"],
["Placement from CSE in 2017/2018/2019/2020/2021"],
["E-learning platform link"]


]

// Possible responses, in corresponding order

const replies = [
  ["Welcome DRGIT & R Of Engineering !!! How May I Hepl You"],
  ["Hi How may I Help You ? "],
  [
    "MSC, MCA, BE, BTech",
    "BSC, BCA, MCVC",
    "Fantastic, how are you?"
  ],
  [
    "Nothing much",
    "About to go to sleep",
    "Can you guess?",
    "I don't know actually"
  ],
  ["I am infinite"],
  ["I am just a bot", "I am a bot. What are you?"],
  ["The one true God, JavaScript"],
  ["I am nameless", "I don't have a name"],
  ["I love you too", "Me too"],
  ["Have you ever felt bad?", "Glad to hear it"],
  ["Why?", "Why? You shouldn't!", "Try watching TV"],
  ["What about?", "Once upon a time..."],
  ["Tell me a story", "Tell me a joke", "Tell me about yourself"],
  ["Bye", "Goodbye", "See you later"],
  ["Sushi", "Pizza"],
  ["Bro!"],
  ["Great question"],
  ["That's ok","I understand","What do you want to talk about?"],
  ["Please say something :("],
  ["Haha!","Good one!"],
  ["all departments are available such IT,Civil,Mech,Cs,EXTC etc."],
  ["BE, MCA, ME, PHD"],
  ["All information of admission and intake is given in the link https://mitra.ac.in/courses-offered/"],
  ["Office number-07212681246 Email Id-principal@mitra.ac.in"],
  ["Prof. Ram Meghe Square Badnera link https://mitra.ac.in/contact/ "],
  ["Yes college provides campus placements. visit here http://mitra.ac.in/tnp "],
  ["You can view your result here - link C:/Doc/Result.JPG"],
  ["For timetable Click on given link C:/Doc/TimeTable.pdf"],
  ["Company-TCS Section-B Package-7.2 LPA Remark-Digital"],
["Company-TCS Section-C Package-7.2 LPA Remark-Digital"],
["Company-TCS Section-B Package-3.75 LPA Remark-CodeVita"],
["Company-TCS Section-A Package-3.75 LPA Remark-CodeVita"],
["Company-TCS Section-A Package-3.75 LPA Remark-CodeVita"],
["Company-TCS Section-B Package-3.75 LPA Remark-CodeVita"],
["Company-TCS Section-B Package-3.75 LPA Remark-InfraMind"],
["Company-TCS Section-C Package-3.75 LPA Remark-Ninja"],
["Company-TCS Section-C Package-3.75 LPA Remark-Ninja"],
["Company-TCS Section-C Package-3.75 LPA Remark-Ninja"],

["Company-TCS Section-C Package-3.75 LPA Remark-Ninja"],
["Company-TCS Section-C Package-3.75 LPA Remark-Ninja"],
["Company-TCS Section-B Package-3.75 LPA Remark-Ninja"],
["Company-TCS Section-B Package-3.75 LPA Remark-Ninja"],
["Company-TCS Section-B Package-3.75 LPA Remark-Ninja"],
["Company-TCS Section-B Package-3.75 LPA Remark-Ninja"],
["Company-TCS Section-B Package-3.75 LPA Remark-Ninja"],
["Company-TCS Section-B Package-3.75 LPA Remark-Ninja"],
["Company-TCS Section-B Package-3.75 LPA Remark-Ninja"],
["Company-TCS Section-B Package-3.75 LPA Remark-Ninja"],
["Company-TCS Section-B Package-3.75 LPA Remark-Ninja"],
["Company-TCS Section-B Package-3.75 LPA Remark-Ninja"],
["Company-TCS Section-A Package-3.75 LPA Remark-Ninja"],
["Company-TCS Section-A Package-3.75 LPA Remark-Ninja"],
["Company-TCS Section-A Package-3.75 LPA Remark-Ninja"],
["Company-TCS Section-A Package-3.75 LPA Remark-Ninja"],
["Company-TCS Section-A Package-3.75 LPA Remark-Ninja"],
["Company-TCS Section-A Package-3.75 LPA Remark-Ninja"],
["Company-TCS Section-A Package-3.75 LPA Remark-Ninja"],
["Company-TCS Section-A Package-3.75 LPA Remark-Ninja"],


["Company-TCS Section-A Package-3.75 LPA Remark-Ninja"],
["Company-TCS Section-A Package-3.75 LPA Remark-Ninja"],
["Company-Capgemini Section-B Package-3.8 LPA"],
["Company-Capgemini Section-C Package-3.8 LPA"],
["Company-Capgemini Section-A Package-3.8 LPA"],
["Company-Capgemini Section-C Package-3.8 LPA"],
["Company-Capgemini Section-C Package-3.8 LPA"],
["Company-Capgemini Section-B Package-3.8 LPA"],
["Company-Capgemini Section-B Package-3.8 LPA"],
["Company-Cognizant Section-A Package-3.5 LPA"],

["Dr. A. P. Bodkhe"],
["Dr. G. R. Bamnote"],
["2019 - 538 students and 2020 - 585 students"],
["Section A, section B, section C"],
["Prof. Ms. S. V. Kalbande"],
["Grade A"],
["Dr. Nitin R. Dhande"],
["In year 1983"],
["251"],
["For open catagory - 1,06,000 rs ; for OBC - 54,000 ; for SC- No fees ; for TFWS scholarship holders - 10,000"],
["https://sgbau.ucanapply.com/smartexam/public/result-details"],
["180 students"],
["https://sgbau.ucanapply.com/smartexam/public/"],
["2017 - 60; 2018 - 69; 2019 - 115; 2020 - 102; 2021 - 79."],
["https://cse-mitra.in/login/index.php"]

]

// Random for any other user input

const alternative = [
  "Same",
  "Go on...",
  "Bro...",
  "Try again",
  "I'm listening...",
  "I don't understand :/"
]

// Whatever else you want :)

const coronavirus = ["Please stay home", "Wear a mask", "Fortunately, I don't have COVID", "These are uncertain times"]